import { boolean, integer, pgTable, serial, text, timestamp } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  uid: text('uid').notNull().unique(),
  email: text('email').notNull(),
  name: text('name'),
  role: text('role').notNull().default('admin'),
  avatar: text('avatar'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const siteSettings = pgTable('site_settings', {
  id: serial('id').primaryKey(),
  companyName: text('company_name').notNull().default('EquipWorkforce Solutions'),
  tagline: text('tagline').notNull().default('Global Manpower & Technical Staffing Solutions'),
  description: text('description').default('Premier international manpower supply and recruitment agency specializing in heavy engineering, construction, oil & gas, logistics, facility management, and healthcare staffing.'),
  email: text('email').notNull().default('contact@equipworkforce.com'),
  phone: text('phone').notNull().default('+44 20 7946 0920'),
  whatsapp: text('whatsapp').notNull().default('+447946092000'),
  address: text('address').notNull().default('100 Bishopsgate, Level 24, London EC2N 4AG, United Kingdom'),
  googleMapsUrl: text('google_maps_url').default('https://maps.google.com/?q=100+Bishopsgate+London'),
  googleMapsEmbedUrl: text('google_maps_embed_url').default(''),
  companyProfilePdfUrl: text('company_profile_pdf_url').default('/uploads/EquipWorkforce_Company_Profile.pdf'),
  companyProfilePdfName: text('company_profile_pdf_name').default('EquipWorkforce_Company_Profile.pdf'),
  businessHours: text('business_hours').notNull().default('Mon - Fri: 08:00 - 18:00 GMT'),
  facebookUrl: text('facebook_url').default('https://facebook.com/equipworkforce'),
  instagramUrl: text('instagram_url').default('https://instagram.com/equipworkforce'),
  linkedinUrl: text('linkedin_url').default('https://linkedin.com/company/equipworkforce'),
  youtubeUrl: text('youtube_url').default('https://youtube.com/@equipworkforce'),
  tiktokUrl: text('tiktok_url').default(''),
  logoUrl: text('logo_url').default(''),
  darkLogoUrl: text('dark_logo_url').default(''),
  footerLogoUrl: text('footer_logo_url').default(''),
  faviconUrl: text('favicon_url').default(''),
  defaultSeoTitle: text('default_seo_title').default('EquipWorkforce – International Manpower & Workforce Solutions'),
  defaultSeoDesc: text('default_seo_desc').default('Enterprise manpower recruitment and global workforce staffing solutions for multinational projects.'),
  defaultOgImage: text('default_og_image').default('/uploads/hero_workforce_logistics_1790187512878.jpg'),
  analyticsId: text('analytics_id').default(''),
  // Hero and Homepage Banner Editable Fields
  heroKicker: text('hero_kicker').default('Accredited Workforce Supplier · ISO 9001 & ISO 45001'),
  heroTitle: text('hero_title').default('International Technical Manpower & Industrial Staffing Solutions'),
  heroSubtitle: text('hero_subtitle').default('Supplying turnkey, trade-tested, and certified workforce squads for civil mega-projects, oil & gas turnarounds, automated maritime ports, and critical infrastructure worldwide.'),
  heroBannerImage: text('hero_banner_image').default('/uploads/hero_workforce_logistics_1790187512878.jpg'),
  heroBannerOpacity: integer('hero_banner_opacity').default(65),
  heroPrimaryCtaText: text('hero_primary_cta_text').default('Request Manpower Quotation'),
  heroPrimaryCtaLink: text('hero_primary_cta_link').default('/request-manpower'),
  heroSecondaryCtaText: text('hero_secondary_cta_text').default('Explore Services'),
  heroSecondaryCtaLink: text('hero_secondary_cta_link').default('/services'),
  heroStat1Value: text('hero_stat1_value').default('18,500+'),
  heroStat1Label: text('hero_stat1_label').default('Specialists Deployed'),
  heroStat2Value: text('hero_stat2_value').default('99.4%'),
  heroStat2Label: text('hero_stat2_label').default('Trade Exam Pass Rate'),
  heroStat3Value: text('hero_stat3_value').default('48-Hour'),
  heroStat3Label: text('hero_stat3_label').default('Rapid Mobilization'),
  heroStat4Value: text('hero_stat4_value').default('24/7'),
  heroStat4Label: text('hero_stat4_label').default('Operations Desk'),
  // Footer Editable Fields
  footerBio: text('footer_bio').default('International manpower supply and technical staffing solutions for mega-scale industrial, engineering, and offshore construction projects.'),
  footerComplianceBadges: text('footer_compliance_badges').default('ISO 9001:2015 & ISO 45001 Certified · Zero-Harm HSE Standards'),
  footerCopyrightText: text('footer_copyright_text').default('© 2026 EquipWorkforce Global. All rights reserved.'),
  footerQuickLinksTitle: text('footer_quick_links_title').default('Workforce Solutions'),
  footerIndustriesTitle: text('footer_industries_title').default('Industries Served'),
  footerContactTitle: text('footer_contact_title').default('Operational Contacts'),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const services = pgTable('services', {
  id: serial('id').primaryKey(),
  title: text('title').notNull(),
  slug: text('slug').notNull().unique(),
  shortDesc: text('short_desc').notNull(),
  fullDesc: text('full_desc').notNull(),
  featuredImage: text('featured_image'),
  icon: text('icon').default('Briefcase'),
  benefits: text('benefits').default('[]'),
  industries: text('industries').default('[]'),
  seoTitle: text('seo_title'),
  seoDesc: text('seo_desc'),
  isPublished: boolean('is_published').notNull().default(true),
  isFeatured: boolean('is_featured').notNull().default(false),
  displayOrder: integer('display_order').notNull().default(0),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const workforceCategories = pgTable('workforce_categories', {
  id: serial('id').primaryKey(),
  title: text('title').notNull(),
  slug: text('slug').notNull().unique(),
  description: text('description').notNull(),
  image: text('image'),
  skills: text('skills').default('[]'),
  experienceInfo: text('experience_info'),
  relatedIndustries: text('related_industries').default('[]'),
  isFeatured: boolean('is_featured').notNull().default(false),
  displayOrder: integer('display_order').notNull().default(0),
  seoTitle: text('seo_title'),
  seoDesc: text('seo_desc'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const industries = pgTable('industries', {
  id: serial('id').primaryKey(),
  title: text('title').notNull(),
  slug: text('slug').notNull().unique(),
  description: text('description').notNull(),
  image: text('image'),
  icon: text('icon').default('Building2'),
  stats: text('stats'),
  displayOrder: integer('display_order').notNull().default(0),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const portfolio = pgTable('portfolio', {
  id: serial('id').primaryKey(),
  title: text('title').notNull(),
  slug: text('slug').notNull().unique(),
  client: text('client').notNull(),
  industry: text('industry').notNull(),
  location: text('location').notNull(),
  year: text('year').notNull(),
  description: text('description').notNull(),
  featuredImage: text('featured_image'),
  gallery: text('gallery').default('[]'),
  servicesProvided: text('services_provided').default('[]'),
  workforceCategories: text('workforce_categories').default('[]'),
  status: text('status').notNull().default('Completed'),
  isFeatured: boolean('is_featured').notNull().default(false),
  seoTitle: text('seo_title'),
  seoDesc: text('seo_desc'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const blogPosts = pgTable('blog_posts', {
  id: serial('id').primaryKey(),
  title: text('title').notNull(),
  slug: text('slug').notNull().unique(),
  excerpt: text('excerpt').notNull(),
  content: text('content').notNull(),
  featuredImage: text('featured_image'),
  author: text('author').notNull().default('EquipWorkforce Editorial'),
  category: text('category').notNull().default('Workforce Insights'),
  tags: text('tags').default('[]'),
  seoTitle: text('seo_title'),
  seoDesc: text('seo_desc'),
  canonicalUrl: text('canonical_url'),
  status: text('status').notNull().default('published'),
  isFeatured: boolean('is_featured').notNull().default(false),
  publishedAt: timestamp('published_at').defaultNow(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const testimonials = pgTable('testimonials', {
  id: serial('id').primaryKey(),
  clientName: text('client_name').notNull(),
  clientRole: text('client_role').notNull(),
  clientCompany: text('client_company').notNull(),
  avatar: text('avatar'),
  quote: text('quote').notNull(),
  rating: integer('rating').notNull().default(5),
  projectTitle: text('project_title'),
  isFeatured: boolean('is_featured').notNull().default(true),
  displayOrder: integer('display_order').notNull().default(0),
  createdAt: timestamp('created_at').defaultNow(),
});

export const faqs = pgTable('faqs', {
  id: serial('id').primaryKey(),
  question: text('question').notNull(),
  answer: text('answer').notNull(),
  category: text('category').notNull().default('General'),
  displayOrder: integer('display_order').notNull().default(0),
  isPublished: boolean('is_published').notNull().default(true),
  createdAt: timestamp('created_at').defaultNow(),
});

export const contactSubmissions = pgTable('contact_submissions', {
  id: serial('id').primaryKey(),
  submissionId: text('submission_id').notNull().unique(),
  name: text('name').notNull(),
  email: text('email').notNull(),
  phone: text('phone'),
  country: text('country'),
  subject: text('subject'),
  inquiryType: text('inquiry_type').notNull(),
  message: text('message').notNull(),
  status: text('status').notNull().default('new'),
  notes: text('notes'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const manpowerRequests = pgTable('manpower_requests', {
  id: serial('id').primaryKey(),
  requestNumber: text('request_number').notNull().unique(),
  companyName: text('company_name').notNull(),
  contactPerson: text('contact_person').notNull(),
  email: text('email').notNull(),
  phone: text('phone').notNull(),
  country: text('country').notNull(),
  city: text('city'),
  service: text('service').notNull(),
  manpowerCategory: text('manpower_category').notNull(),
  workerCount: integer('worker_count').notNull().default(1),
  startDate: text('start_date'),
  duration: text('duration'),
  skills: text('skills'),
  experience: text('experience'),
  reqAccommodation: boolean('req_accommodation').notNull().default(false),
  reqTransport: boolean('req_transport').notNull().default(false),
  reqFood: boolean('req_food').notNull().default(false),
  otherReqs: text('other_reqs'),
  preferredContact: text('preferred_contact').notNull().default('email'),
  status: text('status').notNull().default('new'),
  notes: text('notes'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const formOptions = pgTable('form_options', {
  id: serial('id').primaryKey(),
  formType: text('form_type').notNull(),
  fieldName: text('field_name').notNull(),
  label: text('label').notNull(),
  value: text('value').notNull(),
  displayOrder: integer('display_order').notNull().default(0),
  isActive: boolean('is_active').notNull().default(true),
  createdAt: timestamp('created_at').defaultNow(),
});

export const media = pgTable('media', {
  id: serial('id').primaryKey(),
  filename: text('filename').notNull(),
  originalName: text('original_name').notNull(),
  url: text('url').notNull(),
  mimeType: text('mime_type').notNull(),
  size: integer('size').notNull(),
  altText: text('alt_text'),
  title: text('title'),
  createdAt: timestamp('created_at').defaultNow(),
});

export const activityLogs = pgTable('activity_logs', {
  id: serial('id').primaryKey(),
  userEmail: text('user_email').notNull(),
  action: text('action').notNull(),
  entity: text('entity').notNull(),
  entityId: text('entity_id'),
  details: text('details'),
  createdAt: timestamp('created_at').defaultNow(),
});
